#!/usr/bin/env perl
BEGIN {
	use FindBin;
	chdir $FindBin::RealBin;
}
use v5.14;
use warnings;
use strict;

use Pod::Usage;
use Cwd qw/ abs_path /;
use Getopt::Long;
use File::Spec;

use lib 'lib';
use Mdkkoji::Conf;

my %conf = Mdkkoji::Conf::load;

print <<WARNING if $Mdkkoji::Conf::path eq 'config.pl.sample';
예제용 파일인 config.pl.sample을 사용합니다. config.pl.sample을 참고하여 config.pl를 만들거나 --config 옵션으로 지정한 파일이 존재하는지 확인해보세요
WARNING

given(shift) {
	when ('start')  {
		say "starting the server at $conf{port}...";
		exec("$^X start.pl&")
	}
	when ('status') { exec($^X, 'status.pl') }
	when ('init')   {
		system($^X, $0, 'stop');
		exec($^X, 'init.pl')
	}
	when ('stop')   { exec($^X, 'stop.pl') }
	when ('update') { exec($^X, 'update.pl') }
	when ('restart') {
		system($^X, $0, 'stop');
		exec($^X, $0, 'start');
	}
	default {
		pod2usage(-verbose => 99);
	}
}

__END__

=pod

=head1 NAME

mdkkoji

=head1 SYNOPSIS

mdkkoji [ I<options> ] [ I<commands> ]

=head1 COMMANDS

init start stop restart status update

=head1 OPTIONS

--config I<path>

=head1 EXAMPLES

=head2 처음 실행, 혹은 DB초기화

  mdkkoji init

=head2 서버 켜기/끄기/재시작

  mdkkoji start
  mdkkoji stop
  mdkkoji restart

=head3 서버 상태 확인

  mdkkoji status

=head4 문서 색인

  mdkkoji update
