#!/usr/bin/env perl

use v5.14;
use warnings;
use strict;

use FindBin;
use Pod::Usage;
use Cwd qw/ abs_path /;
use Getopt::Long;
use File::Spec;

use lib File::Spec->catdir($FindBin::RealBin, 'lib');
use Mdkkoji::Conf;

chdir $FindBin::RealBin;
my %conf = Mdkkoji::Conf::load;

given(shift) {
	when ('start')  {
		say "starting the server at $conf{port}...";
		exec("$^X start.pl&")
	}
	when ('status') { exec($^X, 'status.pl') }
	when ('init')   { exec($^X, 'init.pl') }
	when ('stop')   { exec($^X, 'stop.pl') }
	when ('update') { exec($^X, 'update.pl') }
	when ('restart') {
		system($^X, $0, 'stop');
		exec($^X, $0, 'start');
	}
	default {
		pod2usage(-verbose => 99);
	}
}

__END__

=pod

=head1 NAME

mdkkoji

=head1 SYNOPSIS

mdkkoji [ I<options> ] [ I<commands> ]

=head1 DESCRIPTION

Perl script for organizing markdown documents.

=head2 Commands

=over 10

=item C<init>

Test configuration and initialize database. 

=item C<start>

Start mdkkoji server.

=item C<stop>

Stop mdkkoji server.

=item C<update>

Update database.

=back

=head2 Options

=over 25

=item C<--config=[filename]>

run with specified config file

=back